import turtle
turtle.penup()
turtle.goto(-235,325)
turtle.right(90)
turtle.write("USED CAR INVENTORY",font=boldfont)
turtle.goto(-235,315)
turtle.write('----------------------------------------',font=boldfont)
turtle.goto(-235,305)
turtle.write('The following car is in inventory:',font=regfont)
turtle.goto(-235,285)
turtle.write('Make:',font=boldfont)
turtle.goto(-170,285)
turtle.write(f'{car.get_make()}',font=regfont)
turtle.goto(-235,265)
turtle.write('Model:',font=boldfont)
turtle.goto(-170,265)
turtle.write(f'{car.get_model()}',font=regfont)
turtle.goto(-235,245)
turtle.write('Mileage:',font=boldfont)
turtle.goto(-140,245)
turtle.write(f'{car.get_mileage()}',font=regfont)
turtle.goto(-235,225)
turtle.write('Price:',font=boldfont)
turtle.goto(-170,225)
turtle.write(f'{car.get_price()}',font=regfont)
turtle.goto(-235,205)
turtle.write('Number of doors:',font=boldfont)
turtle.goto(-70,205)
turtle.write(f'{car.get_doors()}',font=regfont)
turtle.done()